filename="ttl52int.conf"
memory_model="msmall"
target="mmcs51"
source="${PWD}/ttl52api/ttl52int/"
output="${PWD}/ttl52api/ttl52int/objects/"
binaries="${PWD}/ttl52api/ttl52int/objects/"
assembly="${PWD}/ttl52api/ttl52int/assembly/"

